/* license: https://mit-license.org
 * ==============================================================================
 * The MIT License (MIT)
 *
 * Copyright (c) 2021 Albert Moky
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * ==============================================================================
 */
package secp256k1

/*
#include "ecc.h"
#include "micro-ecc/uECC.c"
*/
import "C"

import "unsafe"

// Generate creates a new ECC key pair using the secp256k1 elliptic curve
//
// Wraps the uECC_make_key C function from micro-ecc library
// Generates 32-byte private key and 64-byte public key (uncompressed format without 0x04 prefix)
//
// Returns:
//   - pub - 64-byte ECC public key (secp256k1 curve)
//   - pri - 32-byte ECC private key (secp256k1 curve)
//
// Panics: If key generation fails (uECC_make_key returns non-1 value)
func Generate() (pub, pri []byte) {
	pub = make([]byte, 64)
	pri = make([]byte, 32)
	pubPtr := (*C.uchar)(unsafe.Pointer(&pub[0]))
	priPtr := (*C.uchar)(unsafe.Pointer(&pri[0]))
	res := C.uECC_make_key(pubPtr, priPtr, C.uECC_secp256k1())
	if res != 1 {
		panic("failed to generate ECC private key")
	}
	return pub, pri
}

// GetPublicKey derives the ECC public key from a given private key (secp256k1 curve)
//
// Wraps the uECC_compute_public_key C function from micro-ecc library
//
// Parameters:
//   - pri - 32-byte ECC private key (must be valid secp256k1 private key)
//
// Returns: 64-byte ECC public key if derivation succeeds, nil if failed
func GetPublicKey(pri []byte) []byte {
	pub := make([]byte, 64)
	pubPtr := (*C.uchar)(unsafe.Pointer(&pub[0]))
	priPtr := (*C.uchar)(unsafe.Pointer(&pri[0]))
	res := C.uECC_compute_public_key(priPtr, pubPtr, C.uECC_secp256k1())
	if res == 1 {
		return pub
	}
	return nil
}

// Sign generates an ECC signature for a message digest using a private key (secp256k1 curve)
//
// Wraps the uECC_sign C function from micro-ecc library
// Produces a 64-byte compact signature (R + S components, 32 bytes each)
//
// Parameters:
//   - pri    - 32-byte ECC private key (secp256k1 curve)
//   - digest - Message digest to sign (typically SHA256 hash of original message)
//
// Returns: 64-byte compact ECC signature if signing succeeds, nil if failed
func Sign(pri, digest []byte) []byte {
	sig := make([]byte, 64)
	keyPtr := (*C.uchar)(unsafe.Pointer(&pri[0]))
	digPtr := (*C.uchar)(unsafe.Pointer(&digest[0]))
	sigPtr := (*C.uchar)(unsafe.Pointer(&sig[0]))
	res := C.uECC_sign(keyPtr, digPtr, C.unsigned(len(digest)), sigPtr, C.uECC_secp256k1())
	if res == 1 {
		return sig
	}
	return nil
}

// Verify checks the validity of an ECC signature against a message digest and public key (secp256k1 curve)
//
// Wraps the uECC_verify C function from micro-ecc library
// Validates compact 64-byte signatures generated by the Sign function
//
// Parameters:
//   - pub       - 64-byte ECC public key (secp256k1 curve)
//   - digest    - Message digest used to generate the signature (SHA256 hash)
//   - signature - 64-byte compact ECC signature to verify
//
// Returns: true if signature is valid (matches public key and digest), false otherwise
func Verify(pub, digest, signature []byte) bool {
	keyPtr := (*C.uchar)(unsafe.Pointer(&pub[0]))
	digPtr := (*C.uchar)(unsafe.Pointer(&digest[0]))
	sigPtr := (*C.uchar)(unsafe.Pointer(&signature[0]))
	res := C.uECC_verify(keyPtr, digPtr, C.unsigned(len(digest)), sigPtr, C.uECC_secp256k1())
	return res == 1
}

// SignatureToDER converts a 64-byte compact ECC signature to DER-encoded format
//
// Wraps the ecc_sig_to_der C function for DER serialization
// DER format is standard for interoperability with other crypto libraries/tools
//
// Parameters:
//   - signature - 64-byte compact ECC signature (R + S components)
//
// Returns: DER-encoded signature byte slice (variable length up to 72 bytes)
func SignatureToDER(signature []byte) []byte {
	der := make([]byte, 72)
	sigPtr := (*C.uchar)(unsafe.Pointer(&signature[0]))
	derPtr := (*C.uchar)(unsafe.Pointer(&der[0]))
	cnt := C.ecc_sig_to_der(sigPtr, derPtr)
	return der[:cnt]
}

// SignatureFromDER converts a DER-encoded ECC signature back to 64-byte compact format
//
// Wraps the ecc_der_to_sig C function for DER deserialization
// Reverses the conversion performed by SignatureToDER
//
// Parameters:
//   - der - DER-encoded ECC signature byte slice
//
// Returns: 64-byte compact ECC signature (R + S components)
func SignatureFromDER(der []byte) []byte {
	sig := make([]byte, 64)
	sigPtr := (*C.uchar)(unsafe.Pointer(&sig[0]))
	derPtr := (*C.uchar)(unsafe.Pointer(&der[0]))
	cnt := len(der)
	C.ecc_der_to_sig(derPtr, C.int(cnt), sigPtr)
	return sig
}
